development:
  adapter: postgresql
  encoding: utf8
  database: deploy_test_development
  pool: 5

integration:
  adapter: postgresql
  encoding: utf8
  database: deploy_test_integration
  pool: 5
  username: demo-app
  password: YxKprNHsWutvWzGv